name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'src/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
